eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  hostname: localhost
server:
  port: 8001
spring:
  application:
    name: CSV-SERVICE
